server:
  port: 5500

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comingwindy?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: Y29taW5nd2luZHktaGVhbHRoeS1kaWV0LXNlY3JldC1rZXktMjAyNi1wcm9kLXNlY3VyZQ==
  expiration: 86400000